name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - master  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Cambia esto a tu región

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name servidorUbuntu \
            --deployment-group-name grupoUbuntu \
            --s3-location bucket=myawsbucket-10d,key=subirUbuntu.zip,bundleType=zip