name: Deploy to AWS CodeDeploy

on:
  push:
    branches:
      - master  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Cambia esto a tu región

      - name: Zip the application
        run: |
          echo "Comprimiendo archivo"
          zip -r subirUbuntu.zip . -x '*.git*' '*.github*' 'node_modules/*' 'vendor/*' # Excluye archivos innecesarios

      - name: Upload to S3
        run: |
          aws s3 cp subirUbuntu.zip s3://myawsbucket-10d/subirUbuntu.zip

      - name: Deploy to AWS CodeDeploy
        run: |
          aws deploy create-deployment \
            --application-name ubuntu_codedeploy_02 \
            --deployment-group-name ubuntuGrupoImplementacion \
            --s3-location bucket=myawsbucket-10d,key=subirUbuntu.zip,bundleType=zip